USE [master]
GO

/****** Object:  Database [SchoolManagementDB]    Script Date: 1/10/2022 22:48:50 ******/
CREATE DATABASE [SchoolManagementDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SchoolManagementDB', FILENAME = N'/var/opt/mssql/data/SchoolManagementDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SchoolManagementDB_log', FILENAME = N'/var/opt/mssql/data/SchoolManagementDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SchoolManagementDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SchoolManagementDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SchoolManagementDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SchoolManagementDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SchoolManagementDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SchoolManagementDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET RECOVERY FULL 
GO

ALTER DATABASE [SchoolManagementDB] SET  MULTI_USER 
GO

ALTER DATABASE [SchoolManagementDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SchoolManagementDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SchoolManagementDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SchoolManagementDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SchoolManagementDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SchoolManagementDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SchoolManagementDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SchoolManagementDB] SET  READ_WRITE 
GO


USE [SchoolManagementDB]
GO

IF NOT EXISTS(SELECT 1 FROM SYS.SQL_LOGINS WHERE [name] = 'serviceUser')
BEGIN
/****** Object:  User [service]    Script Date: 31/03/2022 23:37:23 ******/
	CREATE LOGIN serviceUser WITH PASSWORD = 'serviceUser';
END
GO

USE [SchoolManagementDB]
GO
IF NOT EXISTS(SELECT 1 FROM sys.database_principals WHERE NAME = 'serviceUser')
BEGIN
	CREATE USER serviceUser FOR LOGIN serviceUser;
	ALTER AUTHORIZATION ON SCHEMA::db_owner TO serviceUser;
	ALTER AUTHORIZATION ON SCHEMA::db_datareader TO serviceUser;
	ALTER AUTHORIZATION ON SCHEMA::db_datawriter TO serviceUser;
	ALTER ROLE db_owner ADD Member serviceUser;

END
GO